postgres:
  database: se_db
  user: se_user
  password: se_pass
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5

host: 127.0.0.1
port: 8080

page:
  limit: 5
  sorting: 2

redis:
  host: 127.0.0.1
  port: 6379
  db: 1
  minsize: 1
  maxsize: 5
  time: 60